---
title: "Real Wage Growth Rate Forecasts"
author: "Stephan Berke"

execute:
  echo: false
  
bibliography: references.bib
---

> **Abstract.** This project uses a BVAR approach to forecast Australian real wage growth rates
>
> **Keywords.** bvars, impulse responses, quarto, R, real wage growth, inflation

# Introduction

Explain recent history on wages and inflation and why real wages in australia dropped. This is a template repository for the Research Report for **Macroeconometrics**. Learn more about about developing online reports with **quarto** at [quarto.org](https://quarto.org/).

# Research Question

This project aims to forecast real wage growth in Australia.

# Model setup

We will define real wage growth as Real Wage Growth (%) $= (\frac{Nominal \: Wage \: Growth \:(\%)\: -\: Inflation \: Rate \: (\%)}{1\: +\: Inflation \: Rate \: (\%)})$ x 100


# Data

This model utilizes data from the Reserve Bank of Australia and the Australian Bureau of Statistics.
The data is accessed with the R commands  `readrba` and `readabs`.

# Variables

Y - Real wage growth consisting of nominal wage growth and inflation rate

X - Variables
 * Australian Labor Data 
  + Unemployment Rate
  + Labor productivity 
  + Labor participation rate
  + Minimum Wages rate
  + Unionization
  + Demographics
  
 * Global macroeconomic indicators
  + Global GDP growth
  + Technological advances
  + Trade balances

```         
execute:
  echo: true
```

## References {.unnumbered}
